# Generated by Django 3.2.8 on 2021-11-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('rollid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rollname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('rollid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.roll')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.group')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.user')),
            ],
        ),
    ]
