# Generated by Django 4.0 on 2022-02-02 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.role')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.user')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('threadid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('latest', models.CharField(default='new', max_length=100)),
                ('flag', models.CharField(max_length=1)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.user')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=100)),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.group')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.class')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('ptime', models.CharField(default='new', max_length=100)),
                ('flag', models.BooleanField(default=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.user')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=100)),
                ('timed', models.IntegerField()),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.class')),
            ],
            options={
                'unique_together': {('start', 'classid')},
            },
        ),
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.class')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.user')),
            ],
            options={
                'unique_together': {('classid', 'userid')},
            },
        ),
    ]
