# Generated by Django 3.2.8 on 2021-11-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subjename', models.CharField(max_length=10)),
            ],
        ),
    ]
