# Generated by Django 3.2.8 on 2021-11-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0003_alter_subject_subjename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subjename',
            new_name='subjectname',
        ),
    ]
