# Generated by Django 3.2.8 on 2021-11-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0005_subject_subjectnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectnote',
            field=models.CharField(default='なし', max_length=200),
        ),
    ]
