# Generated by Django 3.2.8 on 2021-11-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0006_alter_subject_subjectnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.class')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.user')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=100)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.class')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
