# Generated by Django 3.2.8 on 2021-11-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0007_auto_20211117_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start',
            field=models.CharField(max_length=100),
        ),
    ]
