# Generated by Django 3.2.8 on 2021-11-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0008_auto_20211122_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roll',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='rollid',
            new_name='roleid',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='rollname',
            new_name='rolename',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rollid',
            new_name='roleid',
        ),
    ]
