# Generated by Django 3.2.8 on 2021-11-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0010_event_groupschedule_schedule_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupschedule',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukusuku.group'),
        ),
    ]
