# Generated by Django 3.2.8 on 2021-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0011_alter_groupschedule_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('start', 'classid')},
        ),
    ]
