# Generated by Django 3.2.8 on 2021-12-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0013_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
