# Generated by Django 4.0 on 2021-12-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukusuku', '0014_auto_20211206_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
